FROM heroku/heroku:24-build
USER root
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
  build-essential \
  cmake \
  pkg-config \
  git \
  autoconf \
  automake \
  libtool \
  wget \
  curl \
  libjpeg-dev \
  libpng-dev \
  libtiff-dev \
  libgif-dev \
  libomp-dev

ENV PREFIX=/usr/src/imagemagick

# libde265
ENV LIBDE265_VERSION=1.0.15

RUN curl -L https://github.com/strukturag/libde265/releases/download/v${LIBDE265_VERSION}/libde265-${LIBDE265_VERSION}.tar.gz | tar zx \
  && cd libde265-${LIBDE265_VERSION} \
  && ./autogen.sh \
  && ./configure --prefix=${PREFIX} \
  && make -j"$(nproc)" \
  && make install

# libheif
ENV LIBHEIF_VERSION=1.19.8

RUN curl -L https://github.com/strukturag/libheif/releases/download/v${LIBHEIF_VERSION}/libheif-${LIBHEIF_VERSION}.tar.gz | tar zx \
  && cd libheif-${LIBHEIF_VERSION} \
  && cmake -S . -B build \
       -DCMAKE_BUILD_TYPE=Release \
       -DCMAKE_INSTALL_PREFIX=${PREFIX} \
       -DBUILD_SHARED_LIBS=ON \
       -DWITH_LIBDE265=ON \
       -DWITH_X265=OFF \
       -DWITH_AOM_DECODER=OFF \
       -DWITH_DAV1D=OFF \
       -DWITH_EXAMPLES=ON \
  && cmake --build build --parallel \
  && cmake --install build

# libwebp
ENV LIBWEBP_VERSION=1.5.0

RUN cd /opt \
  && curl -L http://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-${LIBWEBP_VERSION}.tar.gz | tar zx \
  && cd libwebp-${LIBWEBP_VERSION} \
  && ./configure --prefix=${PREFIX} \
  && make -j"$(nproc)" \
  && make install

ENV PATH="${PREFIX}/bin:${PATH}"
ENV CPPPATH="${PREFIX}/include:${CPPPATH}"
ENV CPATH="${PREFIX}/include:${CPATH}"
ENV LIBRARY_PATH="${PREFIX}/lib:${LIBRARY_PATH}"
ENV LD_LIBRARY_PATH="${PREFIX}/lib:${LD_LIBRARY_PATH}"
ENV PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}"

RUN ldconfig ${PREFIX}/lib/

# ImageMagick
ENV IMAGEMAGICK_VERSION=7.1.1-43

RUN cd /usr/src \
  && wget https://github.com/ImageMagick/ImageMagick/archive/refs/tags/${IMAGEMAGICK_VERSION}.tar.gz \
  && tar xf ${IMAGEMAGICK_VERSION}.tar.gz \
  && cd ImageMagick-7* \
  && ./configure \
       --prefix=${PREFIX} \
       --with-heic=yes \
       --with-webp=yes \
       PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig" \
  && make -j"$(nproc)" \
  && make install

RUN cd ${PREFIX} \
  && rm -rf build \
  && mkdir build \
  && tar czf ${PREFIX}/build/imagemagick-heroku-24.tar.gz bin include lib etc share

CMD ["tail", "-f", "/dev/null"]